version: '3.9'

services:
  hls-server:
    image: hls-server
    container_name: ip-camara-streaming-server
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      RTSP_URL: rtsp://192.168.73.237/screenlive
      PORT: 8000
    ports:
      - 8000:8000
    networks:
      - hls-server

networks:
  hls-server:
    driver: bridge
    name: hls-server