version: '3.9'

services:
  rtsp-stream-server:
    image: rtsp-stream-server
    container_name: ip-camara-streaming-server
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      RTSP_URL: rtsp://192.168.73.237/screenlive
      PORT: 8000
      WS_PORT: 9999
    ports:
      - 8000:8000
      - 9999:9999
    networks:
      - rtsp-server

networks:
  rtsp-server:
    driver: bridge
    name: rtsp-server